#!/usr/bin/env bash
# Configure your domain zone so that the
# subdomain www points to your load-balancer IP (lb-01).

display_info() {
    local sub_domain=$1
    local record_type=$2
    local destination=$3
    echo "The subdomain $sub_domain is a $record_type record and points to $destination"
}

get_ip_address() {
    dig +short "$1" | awk '{ print $1 }'
}

# Function to add subdomain to domain
add_subdomain() {
    local domain=$1
    local sub_domain=$2
    local ip_address=$3
    echo "$ip_address $sub_domain.$domain" >> /etc/hosts
}

# Server and load balancer IP addresses
web_01_ip="54.237.218.141"
web_02_ip="34.232.53.132"
lb_01_ip="34.207.188.43"

# Domain Name
domain=$1
sub_domain=$2

# Add subdomains to domain
add_subdomain $domain "www" "$lb_01_ip"
add_subdomain $domain "lb-01" "$lb_01_ip"
add_subdomain $domain "web-01" "$web_01_ip"
add_subdomain $domain "web-02" "$web_02_ip"

# If no subdomain is provided, check default ones
if [ -z "$sub_domain" ]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
    for sub in "${subdomains[@]}"; do
        display_info "$sub" "A" "$(get_ip_address $sub.$domain)"
    done
else
    # If a specific subdomain is provided, display its info
    case $sub_domain in
        "www" | "lb-01" | "web-01" | "web-02")
            display_info "$sub_domain" "A" "$(get_ip_address $sub_domain.$domain)"
            ;;
        *)
            echo "Unknown subdomain: $sub_domain"
            ;;
    esac
fi
