#!/usr/bin/env bash
# Configure your domain zone so that the
# subdomain www points to your load-balancer IP (lb-01).

display_info() {
    local sub_domain=$1
    local record_type=$2
    local destination=$3
    echo "The subdomain $sub_domain is a $record_type record and points to $destination"
}

# Server and load balancer IP addresses
web_01_ip="54.237.218.141"
web_02_ip="34.232.53.132"

# Domain Name
domain=$1
sub_domain=$2

# If no subdomain is provided, check default ones
if [ -z "$sub_domain" ]; then
    display_info "www" "A" "$(dig +short www.$domain)"
    display_info "lb-01" "A" "$(dig +short lb-01.$domain)"
    display_info "web-01" "A" "$web_01_ip"
    display_info "web-02" "A" "$web_02_ip"
else
    # If a specific subdomain is provided, display its info
    case $sub_domain in
        "www")
            display_info "$sub_domain" "A" "$(dig +short www.$domain)"
            ;;
        "lb-01")
            display_info "$sub_domain" "A" "$(dig +short lb-01.$domain)"
            ;;
        "web-01")
            display_info "$sub_domain" "A" "$web_01_ip"
            ;;
        "web-02")
            display_info "$sub_domain" "A" "$web_02_ip"
            ;;
        *)
    esac
fi
