#!/usr/bin/env bash
# Write a Bash script that transfers a file from our client to a server:
# Requirements:
# Accepts 4 parameters
#  1.The path to the file to be transferred
#  2.The IP of the server we want to transfer the file to
#  3.The username scp connects with
#  4.The path to the SSH private key that scp uses
# Display Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY if less than 3 parameters passed
# scp must transfer the file to the user home directory ~/
# Strict host key checking must be disabled when using scp

if [ $# -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# Assign parameters to variables for readability
file_path=$1
server_ip=$2
username=$3
ssh_key=$4

# Use scp to transfer file to user's hom directory
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$server_ip":~/

