#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
# Requirements:
#  The redirection must be a “301 Moved Permanently”
#  You answer file should be a Bash script containing commands to automatically configure a Ubuntu machine to respect above requirements
#  Using what you did with 1-install_nginx_web_server, write 3-redirection so that it configures a brand new Ubuntu machine to the requirements asked in this task

apt-get update

apt-get install -y nginx

echo "Hello World!" | tee /var/www/html/index.nginx-debian.html

service nginx restart

#configure redirection
echo -e "location /redirect_me \n\t\treturn 301 https://youtu.be/dQw4w9WgXcQ; \n\t}\n" >> /etc/nginx/sites-available/default

service nginx restart
