#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.
# Requirements:
#  The page must return an HTTP 404 error code
#  The page must contain the string Ceci n'est pas une page
#  Using what you did with 3-redirection, write 4-not_found_page_404 so that it configures a brand new Ubuntu machine to the requirements asked in this task

apt update

apt install -y nginx

# Configure Nginx to listen on port 80
echo "server {
    listen 80;

    # Configure a custom 404 page
    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
    }
    # Set the default root to serve Hello World! at /
    location / {
        root /var/www/html;
        index index.nginx-debian.html;
    }
}" > /etc/nginx/sites-available/default

# Create a custom 404 page with the required string
echo "Ceci n'est pas une page" | tee /var/www/html/404.html

# Create a sample index page
echo "Hello World!" > /var/www/html/index.nginx-debian.html

service nginx restart
