#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.
# Requirements:
#  The page must return an HTTP 404 error code
#  The page must contain the string Ceci n'est pas une page
#  Using what you did with 3-redirection, write 4-not_found_page_404 so that it configures a brand new Ubuntu machine to the requirements asked in this task

apt update

apt install -y nginx

# Create a custom 404 page with the required string
echo "Ceci n'est pas une page" | tee /var/www/html/404.html

# Configure Nginx to use the custom 404 page
echo -e "error_page 404 /404.html;\nlocation = /404.html {\n    root /var/www/html;\n    internal;\n}" > /etc/nginx/sites-available/default

service nginx restart
