#!/usr/bin/env bash
# configure web-02 to be identical to web-01
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on
# Write 0-custom_http_response_header so that it configures a brand new Ubuntu machine to the requirements asked in this task.

sudo apt-get -y update

sudo apt-get install -y nginx

sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html /var/www/error
sudo chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Define the custom header configuration
HOSTNAME=$(hostname)

# Configure nginx with custom response header, 404 page, and 301 redirect
server_config="server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;

    # Add the custom HTTP header
    add_header X-Served-By \$hostname;

    location / {
        try_files \$uri \$uri/ =404;
    }
    if (\$request_filename ~ redirect_me){
		rewrite ^ https://youtube.com permanent;
	}
	error_page 404 /404.html;
	location = /404.html {
		internal;
	}
}"

# Apply Nginx server configuration
echo "$server_config" | sudo tee /etc/nginx/sites-enabled/default > /dev/null

# Restart Nginx service
sudo service nginx restart
