#!/usr/bin/env bash
# configure web-02 to be identical to web-01
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on
# Write 0-custom_http_response_header so that it configures a brand new Ubuntu machine to the requirements asked in this task.

sudo apt-get update

sudo apt-get install -y nginx

# Define the custom header configuration
HOSTNAME=$(hostname)

# Configure nginx with custom response header, 404 page, and 301 redirect
cat <<EOF | tee /etc/nginx/sites-available/default
server {
    listen 80;
    sever_name _;

    root /etc/nginx/html;
    index index.html;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
    }

    add_header X-Served-By $HOSTNAME;
}
EOF

# Create custom 404 page
echo "Ceci n'est pas une page" | tee /var/www/html/404.html

# Restart nginx service
service nginx restart
