#!/usr/bin/env bash
# configure web-02 to be identical to web-01
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on
# Write 0-custom_http_response_header so that it configures a brand new Ubuntu machine to the requirements asked in this task.

# Update package list and install Nginx
sudo apt-get -y update
sudo apt-get install -y nginx

# Allow Nginx through the firewall
sudo ufw allow 'Nginx HTTP'

# Create web directories and set permissions
sudo mkdir -p /var/www/html /var/www/error
sudo chmod -R 755 /var/www

# Define the custom header configuration
HOSTNAME=$(hostname)
CUSTOM_HEADER="add_header X-Served-By \$HOSTNAME;"

# Nginx server configuration
server_config="server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    
    # Corrected directive: server_name, not sever_name
    server_name _;

    # Custom HTTP header
    $CUSTOM_HEADER

    # 404 page and 301 redirect
    location / {
        try_files \$uri \$uri/ =404;
    }
    if (\$request_filename ~ redirect_me){
		rewrite ^ https://youtube.com permanent;
	}
	error_page 404 /404.html;
	location = /404.html {
		internal;
	}
}"

# Apply Nginx server configuration
echo "$server_config" | sudo tee /etc/nginx/sites-enabled/default > /dev/null

# Restart Nginx service
sudo service nginx restart
