#!/bin/bash
# Install and configure HAproxy on your lb-01 server.
# Requirements:
#  Configure HAproxy so that it sends traffic to web-01 and web-02
#  Distribute requests using a roundrobin algorithm
#  Make sure that HAproxy can be managed via an init script
#  Make sure that your servers are configured with the right hostnames: [STUDENT_ID]-web-01 and [STUDENT_ID]-web-02. If not, follow this tutorial.
#  For your answer file, write a Bash script that configures a new Ubuntu machine to respect the above requirements

# Update the system
sudo apt-get update
sudo apt-get upgrade -y

# Install HAProxy
sudo apt-get install -y haproxy

# Configure HAProxy
web_server_01="34.227.91.11:80"
web_server_02="54.236.46.184:80"

sudo tee /etc/haproxy/haproxy.cfg > /dev/null << EOF
defaults
    mode http
    timeout client 1m
    timeout connect 5s
    timeout server 1m

frontend web
    bind *:80
    default_backend web_servers

backend web_servers
    balance roundrobin
    server 294083-web-01 $web_server_01 check
    server 294083-web-02 $web_server_02 check
EOF

# Check HAProxy configuration
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Enable HAProxy service
sudo systemctl enable haproxy

# Restart HAProxy service
sudo systemctl restart haproxy

# Verify HAProxy status
sudo systemctl status haproxy
