#!/usr/bin/env bash
# Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs.
# Set the listening port to 80 in the Nginx configuration

cp -r /etc/nginx/sites-available/default /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo service nginx restart
