#!/usr/bin/env bash
# Find out what’s keeping your Ubuntu container’s Nginx installation from listening on port 80.
# Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs.

# Set the listening port to 80 in the Nginx configuration
sudo sed -i "s/8080/80/" /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo service nginx restart
