#!/usr/bin/env bash
# Configures a server to listen on port 80 of all the server’s active IPv4 IPs
sed -i 's/listen 80;/listen 80 default_server;/g' /etc/nginx/sites-available/default
service nginx restart
