#!/usr/bin/env bash
# Ensure Nginx is listening on port 80
sudo cp -r /etc/nginx/sites-available/default /etc/nginx/sites-available/
sudo rm -f /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
