#!/usr/bin/env bash
# Ensure Nginx is configured to listen on port 80
sudo rm -f /etc/nginx/sites-enabled/default &&
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
