#!/usr/bin/env bash
# a Bash script that:
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

handle_exit()
{
	rm -f /var/run/myscript.pid
}

trap 'echo "Y U no love me?!"; exit' SIGINT
trap 'echo "I hate the kill command"' SIGTERM
trap 'handle_exit' SIGQUIT

echo "$$" > /var/run/myscript.pid

while true;
do
	echo "To infinity and beyond"
	sleep 2
done
