#!/usr/bin/env bash
# Displays To infinity and beyond indefinitely and adding a sleep 2,
# and I am invincible!!! when receiving a SIGTERM signal.

trap 'echo "I am invincible!!!"; exit 0' SIGTERM
while true
do
	echo "To infinity and beyond"
	sleep 2
done
