#!/usr/bin/env bash
# Using a while loop and case statement to display "bad luck from China" for 4th loop iteration,
# "bad luck from Japan" for the 9th iteration, and "bad luck from Italy" for the 17th iteration.

counter=1

while [ $counter -le 20 ]
do
	case $counter in
	4)
	echo "$counter bad luck from China"
		;;
	9)
	echo "$counter bad luck from Japan"
		;;
	17)
	echo "$counter bad luck from Italy"
		;;
	*)
	echo $counter
		;;
	esac

counter=$((counter+1))
done
