#!/usr/bin/env bash
# Using a if loop to give you information about the school file.
# -e = file exists, -s = file not empty, -f = regular file

file="school"

if [ -e "$file" ]
    then
	echo "school file exists"
    
    if [ -s "$file" ]
     then
	echo "school file is not empty"
    else
	echo "school file is empty"
	fi
    
    if [ -f "$file" ]
     then
	echo "school is a regular file"
     fi
    else
	echo "school file does not exist"
    fi
