#!/usr/bin/env bash
# Configure an Ubuntu server as follows:
#  - localhost resolves to 127.0.0.2
#  - facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.bak

sed -i 's/127.*$/127.0.0.2 localhost/' ~/hosts.bak
sed -i 's/157.240.11.35 facebook.com/8.8.8.8 facebook.com/' ~/hosts.bak

cp -f ~/hosts.bak /etc/hosts
