#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user.

# Set the Nginx user in the Nginx config
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf

# Set Nginx to listen on all active IPs on port 8080
sed -i 's/listen 80 default_server;/listen 8080 default_server;/g' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart
