#!/usr/bin/env bash
# a Bash script that uses ssh to connect to your server using,
# the private key ~/.ssh/school with the user ubuntu.

server="54.160.127.184"
user="ubuntu"
private_key_path="$HOME/.ssh/school"

ssh -i "$private_key_path" "$user"@"$server"
